language: julia

os:
  # linux
  # - osx
  - windows

julia:

  - 1.0
  - 1
  - nightly

notifications:
  email:
    recipients: eleonora.avello@gmail.com
    on-success: never
    on-failure: change

branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\$*)?$/ # tags

jobs:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'if Sys.islinux()
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())
    end'