name = "GrupoBeta"
uuid = "707fce5a-4275-4f78-a87f-7cc8d395dd76"
authors = ["EleonoraAvello, Gustavo Rodrigues, Bianca Natal, Gustavo Martins"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]